[tool.black]
target-version = ["py311"]
required-version = "23.3.0"
quiet = true

[tool.mypy]
strict = true

# need to check type hints in the project code only,
# so suppress warnings about missing annotations in 3rd party code
ignore_missing_imports = true

files = [
    "./tinyurl2/",
]
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]

plugins = [
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra -q --strict-markers"

[tool.coverage.run]
branch = true
source = [
    "./tinyurl2/",
]
omit = [
    "*conftest.py",
    "*/tests/*",
]

[tool.coverage.report]
fail_under = 90
