[tool.black]
target-version = ["py311"]
required-version = "23.3.0"
quiet = true

[tool.docformatter]
in-place = true
recursive = true
black = true

[tool.mypy]
strict = true

# need to check type hints in the project code only,
# so suppress warnings about missing annotations in 3rd party code
ignore_missing_imports = true

files = [
    "./tinyurl2/",
]
exclude = [
    ".*conftest.py",
    ".*/tests/.*",
]

plugins = [
    "pydantic.mypy",
    "sqlalchemy.ext.mypy.plugin",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = [
    "-ra",  # show summary for all except passed tests
    "-q",  # quiet
    "--strict-markers",  # require custom markers to be listed in config
    # skip fully covered files in coverage report
    "--cov-report=term-missing:skip-covered",
]

[tool.coverage.run]
branch = true
source = [
    "./tinyurl2/",
]
omit = [
    "*conftest.py",
    "*/tests/*",
    "*/migrations/*",
]

[tool.coverage.report]
fail_under = 90
