"""initial

Revision ID: 7c685e6c44db
Previous: None
Create Date: 2022-07-02 15:17:25.244056
"""

import sqlalchemy as sa
from alembic import op

revision = "7c685e6c44db"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("url")
    # ### end Alembic commands ###
